export const LANG_TO_CURRENCY: Record<string, { code: string; symbol: string; name: string }> = {
  ja: { code: 'JPY', symbol: '¥', name: 'Japanese Yen' },
  es: { code: 'EUR', symbol: '€', name: 'Euro' },
  fr: { code: 'EUR', symbol: '€', name: 'Euro' },
  ko: { code: 'KRW', symbol: '₩', name: 'Korean Won' },
  zh: { code: 'CNY', symbol: '¥', name: 'Chinese Yuan' },
  en: { code: 'USD', symbol: '$', name: 'US Dollar' },
  pt: { code: 'BRL', symbol: 'R$', name: 'Brazilian Real' },
  de: { code: 'EUR', symbol: '€', name: 'Euro' },
  it: { code: 'EUR', symbol: '€', name: 'Euro' },
  hi: { code: 'INR', symbol: '₹', name: 'Indian Rupee' },
  ar: { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham' },
  th: { code: 'THB', symbol: '฿', name: 'Thai Baht' },
  vi: { code: 'VND', symbol: '₫', name: 'Vietnamese Dong' },
};

export const HOME_CURRENCIES: ReadonlyArray<{ code: string; symbol: string; name: string }> = [
  { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar' },
  { code: 'USD', symbol: '$', name: 'US Dollar' },
  { code: 'EUR', symbol: '€', name: 'Euro' },
  { code: 'GBP', symbol: '£', name: 'British Pound' },
  { code: 'AUD', symbol: 'A$', name: 'Australian Dollar' },
  { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar' },
  { code: 'CHF', symbol: 'Fr', name: 'Swiss Franc' },
  { code: 'JPY', symbol: '¥', name: 'Japanese Yen' },
  { code: 'KRW', symbol: '₩', name: 'Korean Won' },
  { code: 'CNY', symbol: '¥', name: 'Chinese Yuan' },
  { code: 'INR', symbol: '₹', name: 'Indian Rupee' },
  { code: 'BRL', symbol: 'R$', name: 'Brazilian Real' },
  { code: 'MXN', symbol: 'Mex$', name: 'Mexican Peso' },
  { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar' },
  { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar' },
  { code: 'SEK', symbol: 'kr', name: 'Swedish Krona' },
  { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone' },
  { code: 'DKK', symbol: 'kr', name: 'Danish Krone' },
  { code: 'PLN', symbol: 'zł', name: 'Polish Zloty' },
  { code: 'THB', symbol: '฿', name: 'Thai Baht' },
  { code: 'ZAR', symbol: 'R', name: 'South African Rand' },
  { code: 'TRY', symbol: '₺', name: 'Turkish Lira' },
  { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham' },
  { code: 'PHP', symbol: '₱', name: 'Philippine Peso' },
  { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah' },
  { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit' },
  { code: 'VND', symbol: '₫', name: 'Vietnamese Dong' },
  { code: 'COP', symbol: 'COL$', name: 'Colombian Peso' },
  { code: 'CLP', symbol: 'CL$', name: 'Chilean Peso' },
  { code: 'PEN', symbol: 'S/', name: 'Peruvian Sol' },
  { code: 'ARS', symbol: 'AR$', name: 'Argentine Peso' },
  { code: 'ILS', symbol: '₪', name: 'Israeli Shekel' },
  { code: 'EGP', symbol: 'E£', name: 'Egyptian Pound' },
  { code: 'NGN', symbol: '₦', name: 'Nigerian Naira' },
  { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling' },
];
